name: Visual Tests
on:
  pull_request:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build for web server
        run: npx vite build
      - name: Run web server on background
        run: npx vite preview --port 5173 &
      - name: Run Backstop tests
        run: sleep 150 && npm run test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: backstop-report
          path: backstop_data/html_report
          retention-days: 30
