name: Visual Tests
on:
  push:
  pull_request:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: 'Run dev'
        run: npm run dev
      - name: Run Backstop tests
        run: npx backstop test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: backstop-report
          path: backstop_data/html_report
          retention-days: 30
